name: Deploy to Staging S3

on:
  push:
    branches: [ develop, staging ]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Sync files to Staging S3
      run: |
        aws s3 sync . s3://${{ secrets.S3_STAGING_BUCKET_NAME }} \
          --exclude ".git/*" \
          --exclude ".github/*" \
          --exclude "docs/*" \
          --exclude "README.md" \
          --exclude ".DS_Store" \
          --delete
          
    - name: Set staging cache headers
      run: |
        aws s3 cp s3://${{ secrets.S3_STAGING_BUCKET_NAME }}/index.html \
          s3://${{ secrets.S3_STAGING_BUCKET_NAME }}/index.html \
          --metadata-directive REPLACE \
          --cache-control "no-cache, no-store, must-revalidate"